### ISSUE TITLE
Use binary-prefix file sizes

### ISSUE THREAD

**Issue by Wuzzy2** [az0/bleachbit#103]
LOL, I just noticed that BleachBit calculates file sizes in factors of 1000 (1 BleachBit Kilobyte = 1000 Bytes), rather than in factors of 1024. While this is stricly SI-conform, it is very confusing because many operatings systems and programs use 1024 as factor.

The best solution would be to simply switch to binary prefixes:

1 KiB = 1024 B, 1 MiB = 1024 KiB, and so on.

See here: https://en.wikipedia.org/wiki/Binary_prefix#Adoption_by_IEC.2C_NIST_and_ISO

**Comment by az0** [comment]
Since March 2010 BleachBit should be following this policy.

https://wiki.ubuntu.com/UnitsPolicy

If you still think this is an issue, please reopen

**Comment by Wuzzy2** [comment]
I am unable to reopen this issue, but I can still comment on this.

I call bullshit on Ubuntu's UnitsPolicy. It does not account for the fact that the past 25 years or so used factor 1024 for “fake SI” style prefixes (KB, MB, GB, etc.). It is a rather young interpretation that the “correct” factor is 1000, because of SI. No matter in which camp you are, this basically means that there are two competing interpretations of what “1 MB” means, one uses factor 1024 and is far more wide-spread, while the other uses factor 1000. This creates an ambiguity. Whenever you read “1 MB” you can't trust this number unless you know which factor the author has been using.

I still propose to switch to binary-style prefixes (KiB, MiB, GiB, etc.), since this preserves the factor 1024 which has been used for so long and resolves the ambiguity.

**Comment by tiemay** [comment]
Perhaps a compromise?
> For file sizes there are two possibilities:

> 1. Show both, base-10 and base-2 (in this order). An example is the Linux kernel: "2930277168 512-byte hardware sectors: (1.50 TB/1.36 TiB)"
> 1. Only show base-10, or give the user the opportunity to decide between base-10 and base-2 (the default must be base-10). 

Maybe we could do one of those two options?

Also, the KDE system settings lets you choose between IEC and Metric, and most KDE programs abide by that setting. I'm not sure if a GTK application could make use of that or not, but it would be nice.

**Comment by tstenner** [comment]
Is anyone working on this? If no, should this be implemented as "show both" or "make it an option"?

**Comment by az0** [comment]
I am not working on this.

**Comment by az0** [comment]
Fixed by @tstenner's pull request #111
