### ISSUE TITLE
add /usr/share/locale-bundle/kf5/ to locale cleaner?

### ISSUE THREAD

**Issue by two-dogs** [az0/bleachbit#105]
http://git.io/vCOGl package info
http://git.io/vCOZR system info

**Comment by az0** [comment]
Have you tried the latest version of BleachBit from Git? Or are you using BleachBit version 1.8? Recently @tstenner made many improvements.

**Comment by two-dogs** [comment]
i'll look at 1.8 then, thnks

**Comment by tstenner** [comment]
`/usr/share/locale-bundle/`doesn't seem to be in the list (as I don't use openSuSE), but if you attach the output of `find /usr/share/locale-bundle`, I can create a pull request for it.

**Comment by two-dogs** [comment]
http://git.io/vCWjt < as requested output of find /usr/share/locale-bundle , thanks
