### ISSUE TITLE
Exception while running operation 'localizations'

### ISSUE THREAD

**Issue by az0** [az0/bleachbit#110]
Traceback in BleachBit 1.9.2 beta on Slackware 14.1 x86_64 
````
Traceback (most recent call last):
File "/usr/share/bleachbit/Worker.py", line 330, in run_operations
for dummy in self.clean_operation(operation):
File "/usr/share/bleachbit/Worker.py", line 127, in clean_operation
assert(isinstance(operation_options, list))
AssertionError
```
[Strange GUI](http://i.imgur.com/nwAUP8R.jpg) where Localizations is at the top level (not under System)

Reported by [BBUser on the forum](http://bleachbit.sourceforge.net/node/1197)

@tstenner Do you think this is related to changes to put localizations in XML? Would you please mind taking a closer look?

**Comment by tstenner** [comment]
`localizations.xml` defines a cleaner with label `Localizations`, but as there are no options associated with it, it shouldn't be shown at all.
Running it from the tarball (as a user with no prior configuration) also doesn't list it as a cleaner, so right now I have no idea what's causing this.

**Comment by az0** [comment]
I reproduced this by disabling the option "hide irrelevant cleaners"

**Comment by tstenner** [comment]
I can also reproduce this by showing irrelevant cleaners and checking the empty group.
There are three possible workarounds:

1. hide it, even when "hide irrelevant cleaners" is unchecked
2. add a dummy option which does nothing
3. revert 4628796a541b9d83f6025052a0f6eaa7938d0635

With 3, a debug message `../cleaners/localizations.xml' is not usable` is printed, but it's (in my opinion) the cleanest fix for this bug. Should I prepare a pull request for this?

**Comment by az0** [comment]
Those are good options. I prefer #1.

**Comment by tstenner** [comment]
On the other hand I already get the `XY is not usable` debug message 16 times. Option 1 would involve checking every cleaner for dummy actions, removing them and removing every cleaner without any actions. Option 1 skips everything but the last part and is the shortest fix by far.

**Comment by az0** [comment]
c3a0bce2f8d7d79c882cecb0f5b5f0abaf88ebed is short way to do #1, and today I also added two commits that sometimes avoid the "cleaner is not usable" messages.

These "cleaner is not usable" messages will be avoided:
(1) if the application version Y is even in X.Y.Z, or
(2) for deb/rpm installs, or 
(3) if you run ```grep -l os=.windows. cleaners/*xml | xargs rm -f ````
