### ISSUE TITLE
Chocolatey package

### ISSUE THREAD

**Issue by cfoellmann** [az0/bleachbit#115]
I am looking into "repairing" the bleachbit chocolatey package (https://chocolatey.org/packages/bleachbit)!!
It is totally outdated because the maintainer abandoned the package and it was not an "automatic" package. Which means he had to manually submit the new version.

I want to make the choco `bleachbit` package "automatic" which means it will fetch new releases (automatically) regularly.

We need predictable and lasting download urls for all versions!!
Since sourceforge is drifting off into a bad direction I would suggest hosting the files as GitHub releases. Currently sourceforge urls break for all old versions and the bit advantage of package managers is the ability to revert/install older versions if you wish to. But for that to work all old dl urls need to be valid in the future.
If needed you could use https://bintray.com/ to distribute the files.

If you need download stats for the releases and think they are not available on github you can use http://www.somsubhra.com/github-release-stats/?username=az0&repository=bleachbit to get the download_count. The bleachbit repo has no releases so there is no data found by the direkt link. (Working example: http://www.somsubhra.com/github-release-stats/?username=chocolatey&repository=ChocolateyGUI)

**Comment by az0** [comment]
I appreciate your contribution and effort, Christian. I can see you put some thought into it.  Sometimes I wonder about the download counts, though it is hard to tell with my current setup. SourceForge keeps a tally, but most BleachBit downloads are not served through SourceForge.

Ad blockers and disabling JavaScript are tough enough, but if many more people downloaded BleachBit automatically (without visiting the web site) I maybe could not afford to continue development of the project. Therefore, I should not assist, but in the spirit of open source software and convenience, I am also not against it.
