### ISSUE TITLE
[Suggestion] Enhance files overview

### ISSUE THREAD

**Issue by Banasura** [az0/bleachbit#117]
Hi,

I have a suggestion to improve in my opinion the user interface. It would be nice to have a graphical (or not) overview of the files to be deleted, maybe using a tree showing the impacted folders, with the total size of each file.
At least, it would be great to have a textual representation of this in the log, to have a global idea of the files to be targeted by the cleaning.

What do you think about this suggestion?

Thank you for your work!

**Comment by az0** [comment]
Hello Banasura,

Version 1.10 introduced summaries of total file size by option, but otherwise, yes, I agree that this kind of thing would be helpful. In the short term, though, I need to focus on some other priorities, and I would prefer not to leave this ticket open for a long time.
