### ISSUE TITLE
Errors when starting/closing BleachBit

### ISSUE THREAD

**Issue by timvandermeij** [az0/bleachbit#118]
I'm using BleachBit 1.10 on Windows 10 Pro x64. Every time I start or close BleachBit, a message box is shown saying:

<pre>
Errors occurred

See the logfile 'C:\Program Files (x86)\BleachBit\bleachbit.exe.log' for details
</pre>

The following section is placed in that log file for each time the message box appears:

<pre>
exception when getting special folder path for music
Traceback (most recent call last):
  File "bleachbit\Windows.pyo", line 131, in csidl_to_environ
com_error: (-2147467259, 'Niet nader omschreven fout', None, None)

exception when getting special folder path for pictures
Traceback (most recent call last):
  File "bleachbit\Windows.pyo", line 131, in csidl_to_environ
com_error: (-2147467259, 'Niet nader omschreven fout', None, None)

exception when getting special folder path for video
Traceback (most recent call last):
  File "bleachbit\Windows.pyo", line 131, in csidl_to_environ
com_error: (-2147467259, 'Niet nader omschreven fout', None, None)
</pre>

"Niet nader omschreven fout" is Dutch for "Unspecified error" (because I use the Dutch locale on Windows). I think BleachBit may not like the fact that I don't have Music/Pictures/Video folders in the Documents folder (I removed them because I don't use them), however that should cause any errors.

The errors are created at https://github.com/az0/bleachbit/blob/master/bleachbit/Windows.py#L133. Perhaps it should be changed such that it does not constantly show a message box about this (change `logger.exception` to `logger.info`?).

Do you have an idea on how to fix this? Aside from the message boxes BleachBit works as expected. If you need more information, feel free to let me know. Thank you for building this awesome piece of software!

**Comment by az0** [comment]
Your analysis of the issue was correct. As an awkward workaround I think you can avoid the popup message by running bleachbit_console.exe instead of bleachbit.exe.

**Comment by timvandermeij** [comment]
Awesome, thank you for fixing this so quickly! Just curious: do you already have an idea when the next release is planned that contains this fix?

**Comment by az0** [comment]
The plans are not yet clear, but I hope to release an alpha or beta version within a month. I've started working on a "nightly build" type of system too.
