### ISSUE TITLE
Firefox URL Histroy - Clean-up Issue

### ISSUE THREAD

**Issue by brahmastra2016** [az0/bleachbit#121]
Firefox URL History does not get cleaned even when it is selected under Firefox options.

Both Windows and Mac has same issue.

BleachBit version 1.10
GTK version 2.16.6
local_cleaners_dir = C:\Program Files (x86)\cleaners
locale_dir = C:\Program Files (x86)\BleachBit\share\locale\
options_dir = C:\Users\user\AppData\Roaming\BleachBit
personal_cleaners_dir = C:\Users\user\AppData\Roaming\BleachBit\cleaners
system_cleaners_dir = C:\Program Files (x86)\BleachBit\share\cleaners\
locale.getdefaultlocale = ('en_US', 'cp1252')
os.getenv('APPDATA') = C:\Users\user\AppData\Roaming
os.getenv('LocalAppData') = C:\Users\user\AppData\Local
os.getenv('LocalAppDataLow') = C:\Users\user\AppData\LocalLow
os.getenv('Music') = C:\Users\user\Music
os.getenv('USERPROFILE') = C:\Users\user
os.getenv('ProgramFiles') = C:\Program Files (x86)
os.getenv('ProgramW6432') = C:\Program Files
os.getenv('TMP') = C:\Users\user\AppData\Local\Temp
os.path.expanduser('~') = C:\Users\user
platform.win32_ver[1]() = 6.1.7601
platform.platform = Windows-Vista-6.1.7601-SP1
platform.version = 6.1.7601
sys.argv = ['C:\\Program Files (x86)\\BleachBit\\bleachbit.exe']
sys.executable = C:\Program Files (x86)\BleachBit\bleachbit.exe
sys.version = 2.5.4 (r254:67916, Dec 23 2008, 15:10:54) [MSC v.1310 32 bit (Intel)]
win32com.shell.shell.IsUserAnAdmin() = True
__file__ = C:\Program Files (x86)\BleachBit\library.zip\bleachbit\Diagnostic.pyo

**Comment by brahmastra2016** [comment]
on windows7 fixed it by updating sqlite3.dll /python27/dlls

followed the URL instruction

https://deshmukhsuraj.wordpress.com/2015/02/07/windows-python-users-update-your-sqlite3/

**Comment by az0** [comment]
I will check it out. Thanks

**Comment by az0** [comment]
I updated SQLite version 3.8.0.2 to 3.11.1, and git commit c43077dcf55d79f20706da66d1aaacd6e800ee87 should help with the zeroblob issue too
