### ISSUE TITLE
Crash when copy & paste the preview list

### ISSUE THREAD

**Issue by fduraibi** [az0/bleachbit#125]
When I copy the preview list and try to paste it into a text file the application crashes (almost every time). The list is big and has 45869 files to be deleted.

This is the output from the console,

```
(bleachbit.py:27168): Gdk-ERROR **: The program 'bleachbit.py' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 169182 error_code 3 request_code 18 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
Trace/breakpoint trap (core dumped)

```

I wanted to try `--sync` as suggested in the error message but didn't know how

(system Fedora 23 64bit with KDE 5)

**Comment by az0** [comment]
Do you have a problem copying an a similar amount of text with other GTK+ version 2 applications? 

For troubleshooting you can find a list of such applications: https://en.wikipedia.org/wiki/GTK%2B#Uses

**Comment by fduraibi** [comment]
Yes, I just tested it on yumex, which is a python 2 application using GTK+ v2, and got the same crash message.

I am going to close this issue since it is not related to the app itself
