### ISSUE TITLE
Why i can't edit the "path" on Preferences?

### ISSUE THREAD

**Issue by agusmakmun** [az0/bleachbit#143]
It will be difficult for the users when using a hidden folder ("." dot), although ubuntu has nautilus, but there is no setting for the root user.
Anyway, the bleachbit config located in: `~/.config/bleachbit/bleachbit.ini`, what do you think?

![1](https://cloud.githubusercontent.com/assets/7134451/18455852/b8c362da-7976-11e6-8792-820828b34867.png)

![2](https://cloud.githubusercontent.com/assets/7134451/18455858/be341f0c-7976-11e6-8da6-c68ea7bfff8a.png)

**Comment by az0** [comment]
I tested BleachBit  on Ubuntu 16.04 with GTK+ 2.24.30. Whether I was a normal user or root (using `sudo python bleachbit.py`) I could show hidden files like this

1. Start BleachBit
2. Go to the **Preferences**
3. Go to the **Drives** tab
4. Click **Add** button
5. Right-click
6.  Enable **Show hidden files**

So it seems to work fine here. Did you try right clicking?

**Comment by agusmakmun** [comment]
@az0 good catch.. :+1: 
one more again, i found this bleachbit has another shortcut run "as administrator".

![as-adm](https://cloud.githubusercontent.com/assets/7134451/18468877/14bec06c-79d0-11e6-9458-7edebc3cda92.png)
