### ISSUE TITLE
Supress GTK warning messages while running in CLI

### ISSUE THREAD

**Issue by theatre-x** [az0/bleachbit#34]
Is there anyway we can prevent these messages from appearing while running BB from the command line?

"/usr/lib/python2.7/dist-packages/gtk-2.0/gtk/__init__.py:57: GtkWarning: could not open display
  warnings.warn(str(e), _gtk.Warning)"

**Comment by iliaselmatani** [comment]
Fix: #82

**Comment by az0** [comment]
Fixed now thanks to @iliaselmatani !
