### ISSUE TITLE
test with GTK+ 3.4

### ISSUE THREAD

**Issue by az0** [az0/bleachbit#43]
See #36

**Comment by az0** [comment]
For Debian 7 and Ubuntu 12.04 I may need to either support the old GTK 3.4 or maintain a separate branch for GTK 2.  I would prefer not to support both GTK 2 and 3.

With GTK3 and Python 3, yes, I would like to clean up the old code.  There is some Python 2.5 specific code that I use for the Windows build (because Python 2.5 is much smaller than 2.7)

**Comment by moimael** [comment]
I think maintaining the current GTK2 branch as bugfix/security fix only branch for Debian 7 and Ubuntu 12.04 would be enough.

So we could focus on moving on with the new GTK3 branch. 

People using those distributions do not expect to have the latest software.

**Comment by az0** [comment]
This seems reasonable for Linux.  

For Windows, I am still concerned the GTK+ 3 installer will be huge, but GTK 3.4 vs  v3.10 will probably not make much difference and maybe we can find  a way to cut it back.  With GTK+ 2 I was able to cut out some size without drastic measures
