### ISSUE TITLE
Ideas about the project itself

### ISSUE THREAD

**Issue by cfoellmann** [az0/bleachbit#85]
First @az0 thank you for this great project!
I don't know the stats but I think Bleachbit is used by far too few people and needs to replace CCleaner as the standard in peoples minds.
It's all about design and how something is marketed for most people/users.

Some ideas about how to improve the project in unsorted order:
- Link to the chocolatey package: https://chocolatey.org/packages/bleachbit as an install option
- modernize the website (open source project websites do not need to be old-fashined)
  - maybe GitHub Pages (would allow everyone to contribute to the site)
    - maybe I can sponsor a WordPress based site (depending on traffic)
  - maybe bleachbit.org?
- move bleachbit repos to BleachBit GH organization? (would already allow for GH pages under bleachbit.github.io + custom domain support)
- consider www.transifex.com to replace launchpad translation platform

This are just some ideas. What do you think?

**Comment by tiemay** [comment]
It seems everything in the download pages is packaged and maintained by us. I'm not sure what @az0 thinks of third party maintainers, but if we do start adding them, we'll have [quite a few to add](http://pkgs.org/search/bleachbit).

Transifex is a nice platform, easy to use for non-tech-savvy translators, and free for open source projects, but I'm not familiar with the launchpad translation system, so I can't make a comparison. If we where to switch to Transifex, [this documentation](http://chakraos.org/wiki/index.php?title=Transifex) may be helpful.

**Comment by az0** [comment]
I am not sure what the advantage of Transifex is over Launchpad. Do you have any specifics?  What do most translators prefer?  Launchpad has an active community of translators: BleachBit has had over 300 unique translators contribute through Launchpad.

The web site: BleachBit uses the latest version of Drupal, and I would rather change the Drupal template than switch to another system.

**Comment by vgturtle127** [comment]
@az0 @cfoellmann We could also switch from GTK to Qt.

Developers are moving away from GTK in favor of Qt since it is a little more speedy and the interface is a little more unified.

**Comment by cfoellmann** [comment]
is it http://www.qt.io/ide/ ?
Is it open-source?

**Comment by vgturtle127** [comment]
https://www.qt.io/download-open-source/

That is the link to the community/open-source version.

I wouldn't recommend an open-source project use a closed-source GUI toolkit. That would be just silly. :smile: 

Qt makes an IDE for building the GUI and for coding, but you can just use the libraries by themselves, or you can just use the IDE to build the GUI (which is what I do).

Basically, they are separate from each other is what I'm saying.

**Comment by nodiscc** [comment]
* I agree about the Transifex interface being _much_ more usable than Launchpad's, but indeed there are more contributors on Launchpad; so I think the translation platform should remain unchanged.
 * While switching to QT makes sens for projects with large, complex UIs, bleachbit does not full under that category and I think the code is clear and efficient enough.
 * Linking to the chocolatey package would be nice. The other major "package manager" for Windows is [Npackd](http://npackd.appspot.com/) and it provides a [bleachbit package](http://npackd.appspot.com/p/bleachbit), I think it should also have a link.
 * The website is good enough, but it would be better without third-party resources/trackers (google-analytics.com, gstatic.com, addthis.com, googlesyndication.com) on the homepage. The main screenshot is also hosted on googleusercontent.com.

@az0 thoughts?

**Comment by az0** [comment]
I appreciate you discussing these thoughts.

Launchpad is working well for 63 translations, so I agree.

QT: Popularity and speediness are not major drivers. (I am not whether "unified" means the API or the user experience.) I agree BleachBit has a generally simple user interface, so the cost is not as large as other projects, but it is still significant. Major factors include the cost (vs. focusing those development efforts on general bug fixes and enhancements) and how small of an installation package can be created for Windows. I created a [minimal Python+GTK3 program](https://github.com/az0/frozen_pygtk3) for Windows, and it is an astounding 90MB. I would like to see how QT and wxWidgets, which gives a native experience, compare to GTK+ 3. 

The chocolatey and Npackd packages are very stale, which is a major problem.  I am not sure whether they may alter them, like Ubuntu does. Finally,  people that use who use those packaging systems (plus Portable Apps) should know how to find packages for their systems, so they don't really need a link.

Addthis and Google+ seem to add little value, so I will remove them today.

I don't see any issue with the screenshots on googleusercontent.com (which is Picasa Web Albums). Perhaps you could clarify.

People who are bothered by google-analytics and googlesyndication.com often use blockers, though the ads (googlesyndication.com) and driving traffic to the site are important to continue development of this project.

Generally I think of discussions taking place [on a forum](http://bleachbit.sourceforge.net/forum). If you prefer discussions on GitHub issues, then it would be easier to manage and more actionable to create one issue per topic. I am closing this issue not to end this discussion but to ask that you please continue it using one of those two methods. Feel free to add a link in this issue to any future discussions that continue from here. Thank you!

**Comment by vgturtle127** [comment]
@az0 Yeah, you are right about the GUI. I actually really like it, mainly because it is so simple and easy to use. I suggested that more as an alternative to GTK. Upgrading GTK to the latest version would also greatly benefit the project since there would be bugs fixed, improvements, etc. You are right about Qt being better for larger projects and complex UIs. Most of the stuff I use it for are emulators, virtualization, and fairly complex applications, so I never thought anything else would really fit for my use cases.

The GUI itself is really great though.

My issue with those Windows package managers is they never seem to be up to date. That's really my only issue, I can't think of anything else at the moment. Other than maybe the fact you can just download it from the official website and have it installed just as fast.

Anyway, thanks for responding and thanks for being open-minded!

**Comment by az0** [comment]
FYI: moimael has committed the basic changes to update BleachBit for GTK+ version 3, and they are in the [modernization branch]( https://github.com/az0/bleachbit/commits/modernization ). Their release is blocked by several [issues marked modernizations](https://github.com/az0/bleachbit/labels/modernization) plus a lot of rebasing to catch up that branch. I would like to continue that effort after fixing some ugly bugs in the present version.

**Comment by vgturtle127** [comment]
@az0 Alright, I will take a look. Thanks!

**Comment by az0** [comment]
Regarding Christian's original comment, I am in the process of setting up 
1. the BleachBit organization on GitHub https://github.com/bleachbit/
2. the domain bleachbit.org

**Comment by vgturtle127** [comment]
@az0 Cool! :smile:
