### ISSUE TITLE
setup_environment() function on Windows 8

### ISSUE THREAD

**Issue by cfoellmann** [az0/bleachbit#90]
Is it possible that the function `setup_environment()` ( SEE: https://github.com/az0/bleachbit/blob/96500aafb38c0539159b764a53be1fef55988762/bleachbit/Windows.py#L538-L544 ) is broken on Windows >=7?
My issue here https://github.com/az0/cleanerml/pull/61 with the `$MUSIC` variable might be caused by the deprecation of __CSIDL__ https://msdn.microsoft.com/en-us/library/windows/desktop/bb762494%28v=vs.85%29.aspx in Vista.
> The CSIDL system is supported under Windows Vista for compatibility reasons. However, new development should use KNOWNFOLDERID values rather than CSIDL values.

I am running Win 8.1 so it might be possible that CSIDL values are not available anymore!?

**Comment by az0** [comment]
Make sure you are using a recent version of BleachBit (e.g., version 1.7.5) for the MUSIC variable.

**Comment by cfoellmann** [comment]
Maybe you should add the alpha/beta versions to the website in some way to let users know that testers are wanted/needed

**Comment by cfoellmann** [comment]
I tried the 1.7.5 alpha and the `$MUSIC` variable does not work.

**Comment by az0** [comment]
I publish beta versions as [news articles](http://bleachbit.sourceforge.net/news/), mention them in the side bar of most pages, and notify users of beta releases through the application (for users that choose that option).  

For alpha versions I post links in response to specific bug reports, but you could also monitor the page http://sourceforge.net/projects/bleachbit/files/bleachbit/ .  Somewhere SourceForge I think has an RSS feed.

Thank you for testing on 1.7.5.  I test the MUSIC variable on later versions of Windows.  

While GitHub is very convenient for pull requests, Launchpad is more convenient for bug tickets and release management, so I will note your problem in [bug 1352683](https://bugs.launchpad.net/bleachbit/+bug/1352683).  Feel free to add comments in Launchpad or to open new bugs there.

**Comment by tiemay** [comment]
|ω．）つ http://sourceforge.net/projects/bleachbit/rss

You can also limit the number of entries it gives you:
http://sourceforge.net/projects/bleachbit/rss?limit=20

**Comment by az0** [comment]
tiemay: nice find :)

@cfoellmann: BleachBit 1.7.6 now shows the %music% variable in the System Information screen (available through the help menu).  I tried it on Windows 7, and it looked OK.  How does it look on your end?

**Comment by az0** [comment]
If you have a chance to test in 1.7.6+ and it fails, please reopen the ticket.

**Comment by cfoellmann** [comment]
works in 1.7.6 alpha.
