### ISSUE TITLE
 Error on Hebrew file names

### ISSUE THREAD

**Issue by kostiya** [az0/bleachbit#93]
I get an error when BleachBit tries to delete file with Hebrew file name.
For example: נסיון.txt~
![Image of Bug](https://i.imgur.com/fdA9a97.png)

**Comment by az0** [comment]
Which version of BleachBit?

**Comment by kostiya** [comment]
1.8

**Comment by az0** [comment]
Which version of Windows?

Please test two ways
1. On the desktop right click on the file and choose "Shred with BleachBit"
2. In BleachBit from the File menu chose Shred File

Do both give the same result?

Also, I would appreciate you refiling the bug here https://bugs.launchpad.net/bleachbit/

**Comment by kostiya** [comment]
I am using Windows 7 SP1 x64.

1. Same error.
2. The file is properly deleted.

Here is the Bug report in Launchpad : https://bugs.launchpad.net/bleachbit/+bug/1469195

**Comment by az0** [comment]
Thank you.  I will manage the bug ticket from Launchpad.
