### ISSUE TITLE
Appdata support?

### ISSUE THREAD

**Issue by cicku** [az0/bleachbit#97]
Hi,

When is it possible to include an appdata file with the tarball? I'd like to let users find bleachbit in GNOME Software center.

Thanks.

[1]---https://wiki.gnome.org/Initiatives/GnomeGoals/AppDataGnomeSoftware
[2]---http://people.freedesktop.org/~hughsient/appdata/

**Comment by az0** [comment]
Feel free to post pull requests on GitHub, but please file wish tickets on Launchpad. 

In this case there is already a wish ticket
https://bugs.launchpad.net/bleachbit/+bug/1322911

I have it marked for the next release, but it depends on how long it takes to get through the high priority bugs.
