### ISSUE TITLE
  File "/usr/share/bleachbit/GUI.py", line 366, in preview_or_run_operations

### ISSUE THREAD

**Issue by faisal-oead** [az0/bleachbit#98]
Error in Worker()
Traceback (most recent call last):
  File "/usr/share/bleachbit/GUI.py", line 366, in preview_or_run_operations
    raise RuntimeError('test')
RuntimeError: test

**Comment by tiemay** [comment]
What did you do to produce this error? On which operating system? With which version of BleachBit?

**Comment by az0** [comment]
My fault.  Thank you for pointing this out so quickly :)
